[build]
  # Diretório de publicação (raiz do projeto para sites estáticos)
  publish = "."
  
  # Comando de build (não necessário para site estático, mas pode ser usado para otimizações)
  command = "echo 'Site estático - sem build necessário'"

[build.environment]
  # Versão do Node.js
  NODE_VERSION = "18"

# Configurações de redirecionamento e reescrita
[[redirects]]
  from = "/quem-somos"
  to = "/quem-somos.html"
  status = 200

[[redirects]]
  from = "/servicos"
  to = "/servicos.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/contato"
  to = "/contato.html"
  status = 200

[[redirects]]
  from = "/snake"
  to = "/snake.html"
  status = 200

# Fallback para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de segurança e headers
[[headers]]
  for = "/*"
  [headers.values]
    # Segurança HTTPS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Prevenção de clickjacking
    X-Frame-Options = "DENY"
    
    # Prevenção de MIME sniffing
    X-Content-Type-Options = "nosniff"
    
    # XSS Protection
    X-XSS-Protection = "1; mode=block"
    
    # Referrer Policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy básica
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https:;"

# Configurações específicas para arquivos estáticos
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configurações de domínio personalizado
[context.production]
  command = "echo 'Deploy de produção'"

[context.deploy-preview]
  command = "echo 'Deploy de preview'"

[context.branch-deploy]
  command = "echo 'Deploy de branch'"